import type { AxisRuntimeConfig } from '../../src/runtime/runtimeConfig';
import type { RegistrationWorkspace } from '../../src/operations/enterprise/registration/registrationClient';

/** Independent transport/UI fixtures; no backend imports or real credentials. */
export const runtime: AxisRuntimeConfig = {
  backofficeBaseUrl: 'https://backoffice.example.test',
  enterpriseCode: 'platform',
  projectCode: 'example',
  clientContractVersion: 1,
  requestTimeoutMs: 10000,
  browserSessionCsrfCookieName: 'test_csrf',
  assistantMaximumEventBytes: 65536,
  assistantReconnectWindowMs: 1000,
  assistantIdleTimeoutMs: 5000,
};
export const profileBaseUrl = 'https://profile.example.test/nodics/profile';
export const workspace: RegistrationWorkspace = {
  contractVersion: 1,
  owner: 'profile',
  renderer: 'axis.enterprise-registration',
  method: 'PASSWORD',
  endpoints: {
    start: '/nodics/profile/v0/enterprise-access/start',
    verify: '/nodics/profile/v0/enterprise-access/verify',
    resend: '/nodics/profile/v0/enterprise-access/resend',
    status: '/nodics/profile/v0/enterprise-access/status',
    complete: '/nodics/profile/v0/enterprise-access/register',
  },
  presentation: {
    title: 'Join your enterprise',
    subtitle: 'Complete registration',
    emailLabel: 'Email',
    emailHelp: 'Invited email',
    sendLabel: 'Send code',
    codeLabel: 'Code',
    codeHelp: 'Current code',
    verifyLabel: 'Verify',
    resendLabel: 'Resend',
    statusLabel: 'Check progress',
    restartLabel: 'Start again',
    enterpriseLabel: 'Enterprise',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    passwordLabel: 'Password',
    passwordHelp: 'Choose a password',
    recoveryPasswordLabel: 'Original password',
    recoveryPasswordHelp: 'Use the original password',
    completeLabel: 'Complete registration',
    retryLabel: 'Resume',
    workingLabel: 'Working',
    signInLabel: 'Sign in',
    recoveryLabel: 'Forgot password',
    signInPath: '/login',
    recoveryPath: '/forgot-password',
    emailStep: 'Verify email',
    detailsStep: 'Details',
    completeStep: 'Ready',
    sentMessage: 'Sending requested',
    deliveryMessage: 'Delivery unavailable',
    invalidCodeMessage: 'Invalid code',
    lockedCodeMessage: 'Code unavailable',
    resolvingMessage: 'Resolving',
    existingMessage: 'Use sign in',
    noInvitationMessage: 'No invitation',
    completeMessage: 'Complete',
    recoveryMessage: 'Resume',
    statusErrorMessage: 'Progress unavailable',
  },
  constraints: {
    maximumNameLength: 128,
    minimumPasswordLength: 12,
    maximumPasswordLength: 128,
  },
};
export const progress = {
  contractVersion: 1,
  stage: 'VERIFY_EMAIL',
  email: 'alex@example.test',
  codeState: 'PENDING',
  resendAt: '2099-01-01T00:00:00Z',
  expiresAt: '2099-01-01T00:30:00Z',
  deliveryStatus: 'QUEUED',
};

/** Independently published application copy, including an optional deadline label. */
export const applicationWorkspace: RegistrationWorkspace = {
  ...workspace,
  applications: {
    submitPath: '/nodics/profile/v0/enterprise-access/apply',
    maximumNoteLength: 1000,
    presentation: {
      title: 'Apply to an enterprise',
      description: 'Review your application',
      enterpriseLabel: 'Enterprise',
      noteLabel: 'Note',
      noteHelp: 'Application note',
      submitLabel: 'Submit application',
      pendingTitle: 'Application pending',
      pendingMessage: 'Awaiting review',
      previousTitle: 'Application history',
      submittedLabel: 'Submitted',
      deadlineLabel: 'Review deadline',
      pendingLabel: 'Awaiting review',
      approvedLabel: 'Approved',
      rejectedLabel: 'Rejected',
      registeredLabel: 'Registered',
      approvedMessage: 'Setup pending',
      rejectedMessage: 'Application rejected',
      reviewNotConfirmedMessage: 'Review startup unconfirmed',
      withdrawnLabel: 'Withdrawn',
      expiredLabel: 'Expired',
      withdrawLabel: 'Withdraw',
      withdrawConfirm: 'Review withdrawal',
      cancelLabel: 'Cancel',
      resubmitLabel: 'Apply again',
      closedMessage: 'Application closed',
    },
  },
};
